# Generated by Django 3.1 on 2020-09-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('real_name', models.CharField(blank=True, max_length=256)),
                ('tz', models.CharField(blank=True, max_length=256)),
                ('activity_periods', models.ManyToManyField(blank=True, related_name='activity_periods', to='UserActivity.ActivityPeriod')),
            ],
        ),
    ]
